name: Cloudflare 배포

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Repository 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: 의존성 설치
        run: npm ci
        
      - name: Nuxt 빌드
        run: npm run build

      - name: Cloudflare 퍼블리싱
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: portfolio
          directory: .output/public
