name: Cloudflare 배포

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: 의존성 설치
        run: npm ci

      - name: Nuxt 빌드
        run: npx nuxi build --preset=cloudflare_pages

      - name: Cloudflare 퍼블리싱
        run: npx wrangler pages deploy dist --project-name portfolio
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
