name: Cloudflare 배포

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

    steps:
      - name: Repository 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Corepack 활성화
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: 의존성 설치
        run: pnpm install --frozen-lockfile --reporter=append-only

      - name: Nuxt 빌드
        run: pnpm nuxi build --preset=cloudflare_pages
        
      - name: Cloudflare 퍼블리싱
        run: pnpm wrangler pages deploy dist --project-name=portfolio
